api-version: 1.13
name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}

main: ${mainClass}

commands:
    mpx:
        description: Magic Pixel main command
        permission: mpx.interact
        permission-message: You do not have permission to use this command.
        usage: /<command>

permissions:
    mpx.*:
        description: Gives access to all mpx commands
        children:
            mpx.interact: true
    mpx.interact:
        description: Allow user to use mpx command
        default: true
