name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}

main: ${mainClass}

commands:
    mpx:
        description: An example command
        permission: minecraft_slp.mpx
        permission-message: You do not have permission to use this command.
        usage: /<command>

permissions: {}
